### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by rhtyd** [bwsw/cloudstack-ui#606]
Hi I'm trying to build locally using the hidden build script, I get this:

```
╭─bhaisaab@antrix  ~/Lab/apache/cloudstack-ui  ‹master›  [15:38:03]
╰─ॐ > npm i                                                                                                                                          1 ↵
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN @angular/compiler@4.4.4 requires a peer of @angular/core@4.4.4 but none was installed.
npm WARN @angular/compiler-cli@4.4.4 requires a peer of @angular/core@4.4.4 but none was installed.
npm WARN @angular/platform-browser-dynamic@4.3.6 requires a peer of @angular/compiler@4.3.6 but none was installed.
npm WARN @angular/platform-server@4.3.6 requires a peer of @angular/compiler@4.3.6 but none was installed.
╭─bhaisaab@antrix  ~/Lab/apache/cloudstack-ui  ‹master›  [15:38:34]
╰─ॐ > npm rebuild node-sass

> node-sass@4.5.3 install /home/bhaisaab/Lab/apache/cloudstack-ui/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /home/bhaisaab/Lab/apache/cloudstack-ui/node_modules/node-sass/vendor/linux-x64-47/binding.node

> node-sass@4.5.3 postinstall /home/bhaisaab/Lab/apache/cloudstack-ui/node_modules/node-sass
> node scripts/build.js

Binary found at /home/bhaisaab/Lab/apache/cloudstack-ui/node_modules/node-sass/vendor/linux-x64-47/binding.node
Testing binary
Binary is fine
node-sass@4.5.3 /home/bhaisaab/Lab/apache/cloudstack-ui/node_modules/node-sass
╭─bhaisaab@antrix  ~/Lab/apache/cloudstack-ui  ‹master›  [15:38:39]
╰─ॐ > npm run build:aot

> cloudstack-ui@1.49.11 build:aot /home/bhaisaab/Lab/apache/cloudstack-ui
> npm run build-themes && ng build --prod --aot


> cloudstack-ui@1.49.11 build-themes /home/bhaisaab/Lab/apache/cloudstack-ui
> sh ./src/generate-themes.sh

Generating themes
Themes generated successfully
/home/bhaisaab/Lab/apache/cloudstack-ui/node_modules/@angular/cli/models/config/config.js:17
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bhaisaab/Lab/apache/cloudstack-ui/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

npm ERR! Linux 4.10.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:aot"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! cloudstack-ui@1.49.11 build:aot: `npm run build-themes && ng build --prod --aot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cloudstack-ui@1.49.11 build:aot script 'npm run build-themes && ng build --prod --aot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cloudstack-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-themes && ng build --prod --aot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cloudstack-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cloudstack-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bhaisaab/Lab/apache/cloudstack-ui/npm-debug.log
```

**Comment by zolotyx** [comment]
Hi @rhtyd,
Please, try to update node version
8.7.0 is used to build a docker image and in Travis. 
https://travis-ci.org/bwsw/cloudstack-ui/builds/286848642 
Please, let us know if that helps.

**Comment by rhtyd** [comment]
I'l try using the docker image, on my host platform (Ubuntu 17.04 based) I get this with upgraded nodejs 8.x:
(node:27228) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat '/home/bhaisaab/.npm/_cacache/tmp/git-clone-32632b2b/ngrx/entity.es5.js'
(node:27228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

╭─bhaisaab@antrix  ~/Lab/apache/cloudstack-ui  ‹master*›  [16:50:53]
╰─ॐ > nodejs --version                                                                                                                               1 ↵
v8.7.0
╭─bhaisaab@antrix  ~/Lab/apache/cloudstack-ui  ‹master*›  [16:50:59]
╰─ॐ > npm -version
5.4.2

**Comment by zolotyx** [comment]
@rhtyd , did you solve the issue?

**Comment by rhtyd** [comment]
@zolotyx yes, I figured I was using old/incorrect build commands. I used yarn and it worked okay for me.
