### ISSUE TITLE
account-tags.reducers.ts throws an error

### ISSUE THREAD

**Issue by kioie** [bwsw/cloudstack-ui#931]
I cloned the app and tried to run an 

> npm test

 after running 

> npm install

I got the below error

```
> cloudstack-ui@1.410.17 test /Users/apples/Desktop/cloudstack-ui-master
> ng test --code-coverage --watch=false

 10% building modules 1/1 modules 0 active                                         
START:
29 01 2018 12:02:28.941:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
29 01 2018 12:02:28.943:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
29 01 2018 12:02:28.949:INFO [launcher]: Starting browser Chrome
29 01 2018 12:02:29.437:ERROR [karma]: Error: src/app/reducers/account-tags/redux/account-tags.reducers.ts(76,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((searchElement: string, fromIndex?: number) => number) | ((searchElement: number, fromIndex?: nu...' has no compatible call signatures.
src/app/reducers/vm/redux/vm-creation.effects.ts(223,20): error TS2345: Argument of type '(res: string) => Observable<boolean> | Observable<BaseTemplateModel>' is not assignable to parameter of type '(value: string, index: number) => ObservableInput<boolean>'.
  Type 'Observable<boolean> | Observable<BaseTemplateModel>' is not assignable to type 'ObservableInput<boolean>'.
    Type 'Observable<BaseTemplateModel>' is not assignable to type 'ObservableInput<boolean>'.
      Type 'Observable<BaseTemplateModel>' is not assignable to type 'ArrayLike<boolean>'.
        Property 'length' is missing in type 'Observable<BaseTemplateModel>'.

    at Compiler.compiler.plugin (/Users/apples/Desktop/cloudstack-ui-master/node_modules/@angular/cli/plugins/karma-webpack-throw-error.js:10:23)
    at Compiler.applyPlugins (/Users/apples/Desktop/cloudstack-ui-master/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/apples/Desktop/cloudstack-ui-master/node_modules/webpack/lib/Compiler.js:105:17)
    at onCompiled (/Users/apples/Desktop/cloudstack-ui-master/node_modules/webpack/lib/Compiler.js:55:18)
    at applyPluginsAsync.err (/Users/apples/Desktop/cloudstack-ui-master/node_modules/webpack/lib/Compiler.js:510:14)
    at next (/Users/apples/Desktop/cloudstack-ui-master/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/Users/apples/Desktop/cloudstack-ui-master/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/Users/apples/Desktop/cloudstack-ui-master/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/Users/apples/Desktop/cloudstack-ui-master/node_modules/webpack/lib/Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (/Users/apples/Desktop/cloudstack-ui-master/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/Users/apples/Desktop/cloudstack-ui-master/node_modules/webpack/lib/Compilation.js:680:19)
    at next (/Users/apples/Desktop/cloudstack-ui-master/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Users/apples/Desktop/cloudstack-ui-master/node_modules/webpack/lib/ProgressPlugin.js:123:6)
    at Compilation.applyPluginsAsyncSeries (/Users/apples/Desktop/cloudstack-ui-master/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/apples/Desktop/cloudstack-ui-master/node_modules/webpack/lib/Compilation.js:671:11)
    at next (/Users/apples/Desktop/cloudstack-ui-master/node_modules/tapable/lib/Tapable.js:202:11)
npm ERR! Test failed.  See above for more details.

```

Looks like the error is originating from this file

> src/app/reducers/account-tags/redux/account-tags.reducers.ts

Thoughts on what could be the issue?

**Comment by Voltisky** [comment]
Same here

**Comment by bwsw** [comment]
hello, @Voltisky @kioie 
Today 1.410.18 is released, try it. Also, to help you discover the things, take a look at our Travis CI logs for environment, It passes the build:
https://travis-ci.org/bwsw/cloudstack-ui/builds/334632529

**Comment by Voltisky** [comment]
@bwsw, Thanks for answer. Problem in my case was outdated yarn. @kioie

**Comment by kioie** [comment]
@Voltisky what version of yarn did you update to?

**Comment by Voltisky** [comment]
@kioie , currently working on yarn v1.3.2.

**Comment by bwsw** [comment]
@kioie @Voltisky 
Can we close it?

**Comment by kioie** [comment]
Hi, apologies for my late response, @Voltisky's guide worked for me.

**Comment by bwsw** [comment]
@kioie Thanks, great.
